require(e1071)
m0_data<-read.csv(file = "data.csv",header = TRUE)
m0_data$Class <- as.factor(m0_data$Class)
svm_model<-svm(Class ~ ., data = m0_data,kernel = "linear")
m_res<-predict(svm_model,newdata = m0_data)
table(m0_data$Class,m_res,dnn = c("Actual","Predicted"))
plot(svm_model,m0_data)

m1_data<-read.csv(file = "data1.csv",header = TRUE)
m1_data$Class <- as.factor(m1_data$Class)
t_res<-predict(svm_model,newdata = m1_data)
table(m1_data$Class,t_res,dnn = c("Actual","Predicted"))
plot(svm_model,m1_data)
