library(fpc);library(png)
img<-readPNG('example.png')
mimg<-as.matrix(img[,,2])
dim(mimg)
ind<-which(mimg!= 1, arr.ind=TRUE)
s<-sample(1:dim(ind)[1],2000,replace=FALSE)
sind<-ind[s,c(2,1)]
set.seed(2)
ds<-dbscan(sind,10.5,MinPts = 7,method="hybrid",seeds=FALSE,showplot=0)
plot(ds, sind)
ds1<-dbscan(sind,10.5,MinPts = 7,method="raw",seeds=TRUE,showplot=0)
plot(ds1, sind)
ds2<-dbscan(sind,10.5,MinPts = 8,method="raw",seeds=FALSE,showplot=0)
plot(ds2, sind)
ds33<-dbscan(sind,10.5,MinPts = 9,method="hybrid",seeds=TRUE,showplot=0)
plot(ds3, sind)
ds4<-dbscan(sind,10.5,MinPts = 10,method="raw",seeds=TRUE,showplot=0)
plot(ds4, sind)
